// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCM8NM_tJTo5QL65mV_W4HDaGFrDb-NaE',
    appId: '1:670366348356:web:af97a5131a8d696fc4b811',
    messagingSenderId: '670366348356',
    projectId: 'todoquest-7952e',
    authDomain: 'todoquest-7952e.firebaseapp.com',
    storageBucket: 'todoquest-7952e.firebasestorage.app',
    measurementId: 'G-ZEMLMGKMXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdyObaaoXrStAMJ_NsD-36zE4joF9zaE',
    appId: '1:670366348356:android:bbe6accf8cd2dbbdc4b811',
    messagingSenderId: '670366348356',
    projectId: 'todoquest-7952e',
    storageBucket: 'todoquest-7952e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfSOqFRqN6pAeXA6lqX9TvbX8o0YCpwGk',
    appId: '1:670366348356:ios:6df2dcffcbb4f239c4b811',
    messagingSenderId: '670366348356',
    projectId: 'todoquest-7952e',
    storageBucket: 'todoquest-7952e.firebasestorage.app',
    iosBundleId: 'kr.sik.todoQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfSOqFRqN6pAeXA6lqX9TvbX8o0YCpwGk',
    appId: '1:670366348356:ios:6df2dcffcbb4f239c4b811',
    messagingSenderId: '670366348356',
    projectId: 'todoquest-7952e',
    storageBucket: 'todoquest-7952e.firebasestorage.app',
    iosBundleId: 'kr.sik.todoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCM8NM_tJTo5QL65mV_W4HDaGFrDb-NaE',
    appId: '1:670366348356:web:508c4639689e4dc4c4b811',
    messagingSenderId: '670366348356',
    projectId: 'todoquest-7952e',
    authDomain: 'todoquest-7952e.firebaseapp.com',
    storageBucket: 'todoquest-7952e.firebasestorage.app',
    measurementId: 'G-WR3G8Y9PTP',
  );
}
